### ISSUE TITLE
Node 12.16.0 builds are broken for core package

### ISSUE THREAD

**Issue by talam** [walmartlabs/cookie-cutter#64]
[Node 12 builds](https://travis-ci.org/walmartlabs/cookie-cutter/jobs/650025283
) are currently broken for the `core` package. A recent update in Travis CI to `12.16.0` is causing the following errors:
```
 FAIL  src/__test__/config.test.ts
  ● Sections › parses empty object and preserves defaults
    TypeError: Class constructor  cannot be invoked without 'new'
      at Object.descriptor.set (src/config.ts:4044:35)
      at apply (src/config.ts:3935:19)
      at Object.parse (src/config.ts:3973:5)
      at Object.<anonymous> (src/__test__/config.test.ts:373:31)
  ● Sections › applies value provided
    TypeError: Class constructor  cannot be invoked without 'new'
      at Object.descriptor.set (src/config.ts:4044:35)
      at apply (src/config.ts:3935:19)
      at Object.parse (src/config.ts:3973:5)
      at Object.<anonymous> (src/__test__/config.test.ts:380:31)
```

The issue seems to only be happening with `RootConfig` but not with the other classes in that file for some odd reason.

**Comment by plameniv** [comment]
I’ve identified what changed in `12.16` that causes the `TypeError: Class constructor  cannot be invoked without 'new'`
The following code is used to determine if the variable passed to `config.field(...)` is a convertFn or not:
`SubSection as any).__proto__.name.length`.

The return value in `12.15.0` and lower versions is `10`.
The return value in `12.16.0` is `0`.

Since the function returns the wrong value, we attempt to call a class without the `new` keyword.
